"""Centralized SQL queries for the Vehicle Quality Command Center."""

T = "VEHICLE_QUALITY_DB.PUBLIC"

# ── Executive Command Center ──────────────────────────────────────────

KPI_OVERVIEW = f"""
SELECT
    COUNT(DISTINCT CAR_ID) AS total_vehicles,
    COUNT(*) AS total_events,
    SUM(HAS_ERROR) AS total_failures,
    ROUND(SUM(HAS_ERROR)::FLOAT / NULLIF(COUNT(*), 0) * 100, 2) AS failure_rate_pct,
    COUNT(DISTINCT CASE WHEN HAS_ERROR = 1 THEN CAR_ID END) AS vehicles_with_failures
FROM {T}.FACT_QUALITY_EVENTS
"""

HIGH_RISK_VEHICLES = f"""
SELECT COUNT(*) AS high_risk_count
FROM {T}.VEHICLE_RISK_SCORE WHERE RISK_TIER IN ('CRITICAL', 'HIGH')
"""

FLEET_HEALTH_BUCKETS = f"""
SELECT RISK_TIER AS status, COUNT(*) AS vehicle_count
FROM {T}.VEHICLE_RISK_SCORE
GROUP BY RISK_TIER
"""

WEEKLY_FAILURE_TREND = f"""
SELECT WEEK_START,
    SUM(TOTAL_EVENTS) AS total_events,
    SUM(FAILURE_COUNT) AS failures,
    ROUND(SUM(FAILURE_COUNT)::FLOAT / NULLIF(SUM(TOTAL_EVENTS), 0) * 100, 2) AS failure_rate_pct,
    SUM(VEHICLES_AFFECTED) AS vehicles_affected
FROM {T}.AGG_FAILURE_RATES
GROUP BY WEEK_START ORDER BY WEEK_START
"""

SUPPLIER_RISK_RANKING = f"""
SELECT SUPPLIER_NAME, TOTAL_EVENTS, TOTAL_FAILURES,
       OVERALL_FAILURE_RATE AS failure_rate_pct,
       RELIABILITY_SCORE, SUPPLIER_STATUS
FROM {T}.SUPPLIER_SCORECARD
ORDER BY OVERALL_FAILURE_RATE DESC
"""

FORECAST_SUMMARY = f"""
SELECT SUM(FORECAST) AS total_predicted_failures
FROM {T}.FORECAST_FAILURES_30D
"""

ERROR_CODE_DISTRIBUTION = f"""
SELECT e.DTC_CODE, d.DESCRIPTION AS error_description, COUNT(*) AS event_count
FROM {T}.FACT_QUALITY_EVENTS e
JOIN {T}.DTC_BATTERY_ERROR_CODES d ON e.DTC_ERROR_CODE = d.ERROR_ID
WHERE e.HAS_ERROR = 1
GROUP BY e.DTC_CODE, d.DESCRIPTION ORDER BY event_count DESC
"""

# ── Vehicle Health Monitor ────────────────────────────────────────────

VEHICLE_RISK_LIST = f"""
SELECT VIN, CAR_ID, MODEL_YEAR, VEHICLE_CONFIG, STATE, STATE_AB,
       PART_NUMBER, SUPPLIER_NAME, BATTERY_TYPE_NAME,
       ERROR_COUNT, TOTAL_EVENTS, LAST_EVENT_DATE,
       RISK_SCORE, RISK_TIER
FROM {T}.VEHICLE_RISK_SCORE
ORDER BY RISK_SCORE DESC
"""

VEHICLE_EVENTS = """
SELECT EVENT_DATE, DTC_CODE, ERROR_DESCRIPTION, HAS_ERROR,
       ROUND(AVG_TEMP_F, 1) AS AVG_TEMP_F,
       ROUND(AVG_WIND_SPEED_MPH, 1) AS WIND_SPEED,
       ROUND(DIST_IN_M, 1) AS DISTANCE_MILES,
       SUPPLIER_NAME, BATTERY_TYPE_NAME
FROM VEHICLE_QUALITY_DB.PUBLIC.FACT_QUALITY_EVENTS
WHERE CAR_ID = {car_id}
ORDER BY EVENT_DATE DESC
"""

COMPONENT_DETAILS = """
SELECT *
FROM VEHICLE_QUALITY_DB.PUBLIC.DIM_COMPONENTS
WHERE PART_NUMBER = '{part_number}'
"""

# ── Root Cause Analysis ───────────────────────────────────────────────

RCA_FAILURE_SUMMARY = f"""
SELECT SUPPLIER_NAME, BATTERY_TYPE_NAME, DTC_CODE, ERROR_DESCRIPTION,
       COUNT(*) AS failure_events,
       ROUND(AVG(AVG_TEMP_F), 1) AS avg_temp,
       ROUND(AVG(DIST_IN_M), 1) AS avg_distance,
       ROUND(AVG(AVG_WIND_SPEED_MPH), 1) AS avg_wind,
       COUNT(DISTINCT CAR_ID) AS vehicles_affected
FROM {T}.FACT_QUALITY_EVENTS
WHERE HAS_ERROR = 1
GROUP BY SUPPLIER_NAME, BATTERY_TYPE_NAME, DTC_CODE, ERROR_DESCRIPTION
ORDER BY failure_events DESC
"""

RCA_SANKEY_DATA = f"""
SELECT SUPPLIER_NAME, BATTERY_TYPE_NAME, DTC_CODE, ERROR_DESCRIPTION, STATE,
       COUNT(*) AS flow_count
FROM {T}.FACT_QUALITY_EVENTS WHERE HAS_ERROR = 1
GROUP BY SUPPLIER_NAME, BATTERY_TYPE_NAME, DTC_CODE, ERROR_DESCRIPTION, STATE
ORDER BY flow_count DESC
LIMIT 100
"""

RISK_EXPLANATIONS = f"""
SELECT VIN, CAR_ID, RISK_SCORE, RISK_TIER, ERROR_COUNT,
       SUPPLIER_NAME, BATTERY_TYPE_NAME, PART_NUMBER, STATE_AB,
       DTC_CONTRIBUTION, SUPPLIER_CONTRIBUTION, ENV_CONTRIBUTION,
       USAGE_CONTRIBUTION, AGE_CONTRIBUTION, FORECAST_CONTRIBUTION,
       PRIMARY_RISK_FACTOR, RECOMMENDED_ACTION, SIMILAR_FAILED_VEHICLES
FROM {T}.RISK_EXPLANATION
ORDER BY RISK_SCORE DESC
LIMIT 200
"""

# ── Failure Prediction ────────────────────────────────────────────────

FORECAST_DATA = f"""
SELECT SERIES AS part_number, TS AS forecast_date,
       FORECAST AS predicted_failures, LOWER_BOUND, UPPER_BOUND
FROM {T}.FORECAST_FAILURES_30D ORDER BY SERIES, TS
"""

HISTORICAL_FAILURES = f"""
SELECT PART_NUMBER AS part_number, WEEK_START AS event_date,
       FAILURE_COUNT AS actual_failures
FROM {T}.AGG_FAILURE_RATES ORDER BY PART_NUMBER, WEEK_START
"""

VEHICLE_RISK_TOP = f"""
SELECT VIN, VEHICLE_CONFIG, STATE, SUPPLIER_NAME, BATTERY_TYPE_NAME,
       PART_NUMBER, ERROR_COUNT, RISK_SCORE, RISK_TIER,
       DTC_SCORE, SUPPLIER_SCORE, ENV_STRESS_SCORE, USAGE_SCORE, FORECAST_SCORE
FROM {T}.VEHICLE_RISK_SCORE
ORDER BY RISK_SCORE DESC LIMIT 100
"""

RISK_HEATMAP = f"""
SELECT SUPPLIER_NAME, BATTERY_TYPE_NAME,
       ROUND(SUM(FAILURE_COUNT)::FLOAT / NULLIF(SUM(TOTAL_EVENTS), 0) * 100, 2) AS failure_rate_pct
FROM {T}.AGG_FAILURE_RATES
GROUP BY SUPPLIER_NAME, BATTERY_TYPE_NAME
"""

# ── Recall Simulator ─────────────────────────────────────────────────

RECALL_BASE = f"""
SELECT VIN, CAR_ID, PART_NUMBER, STATE, STATE_AB,
       SUPPLIER_NAME, BATTERY_TYPE_NAME,
       RISK_SCORE, ERROR_COUNT, RISK_TIER
FROM {T}.VEHICLE_RISK_SCORE
"""

# ── Supplier Intelligence ────────────────────────────────────────────

SUPPLIER_SCORECARD_FULL = f"""
SELECT * FROM {T}.SUPPLIER_SCORECARD ORDER BY OVERALL_FAILURE_RATE DESC
"""

SUPPLIER_WEEKLY_TREND = f"""
SELECT WEEK_START, SUPPLIER_NAME,
       ROUND(SUM(FAILURE_COUNT)::FLOAT / NULLIF(SUM(TOTAL_EVENTS), 0) * 100, 2) AS failure_rate_pct
FROM {T}.AGG_FAILURE_RATES
GROUP BY WEEK_START, SUPPLIER_NAME ORDER BY WEEK_START
"""

BATTERY_TYPE_PERFORMANCE = f"""
SELECT BATTERY_TYPE_NAME, SUPPLIER_NAME,
       SUM(TOTAL_EVENTS) AS total_events, SUM(FAILURE_COUNT) AS total_failures,
       ROUND(SUM(FAILURE_COUNT)::FLOAT / NULLIF(SUM(TOTAL_EVENTS), 0) * 100, 2) AS failure_rate_pct
FROM {T}.AGG_FAILURE_RATES
GROUP BY BATTERY_TYPE_NAME, SUPPLIER_NAME ORDER BY failure_rate_pct DESC
"""

# ── Geo Intelligence ─────────────────────────────────────────────────

GEO_STATE_HEALTH = f"""
SELECT * FROM {T}.FLEET_HEALTH_GEO ORDER BY HIGH_RISK_PCT DESC
"""

FAILURES_BY_STATE = f"""
SELECT STATE, STATE_AB, COUNT(*) AS failure_count,
       ROUND(AVG(AVG_TEMP_F), 1) AS avg_temp,
       COUNT(DISTINCT CAR_ID) AS vehicles_affected
FROM {T}.FACT_QUALITY_EVENTS WHERE HAS_ERROR = 1
GROUP BY STATE, STATE_AB ORDER BY failure_count DESC
"""

GEO_VEHICLE_POINTS = f"""
SELECT LATITUDE, LONGITUDE, STATE_AB, HAS_ERROR, SUPPLIER_NAME,
       BATTERY_TYPE_NAME, CAR_ID
FROM {T}.FACT_QUALITY_EVENTS
WHERE LATITUDE IS NOT NULL AND LONGITUDE IS NOT NULL
"""

# ── Action Center ────────────────────────────────────────────────────

EARLY_WARNINGS = f"""
SELECT VIN, CAR_ID, DETECTED_AT, ALERT_TYPE, SEVERITY, EXPLANATION
FROM {T}.EARLY_WARNING_ALERTS ORDER BY DETECTED_AT DESC
"""

ALERTS_BY_SEVERITY = f"""
SELECT SEVERITY, COUNT(*) AS cnt
FROM {T}.EARLY_WARNING_ALERTS GROUP BY SEVERITY
"""

# ── Copilot context ──────────────────────────────────────────────────

COPILOT_SUMMARY = f"""
SELECT COUNT(DISTINCT CAR_ID) AS total_vehicles,
       SUM(HAS_ERROR) AS total_failures,
       ROUND(SUM(HAS_ERROR)::FLOAT / COUNT(*) * 100, 2) AS failure_rate
FROM {T}.FACT_QUALITY_EVENTS
"""

TOP_SUPPLIER_FAILURES = f"""
SELECT SUPPLIER_NAME, OVERALL_FAILURE_RATE AS rate, RELIABILITY_SCORE, SUPPLIER_STATUS
FROM {T}.SUPPLIER_SCORECARD ORDER BY OVERALL_FAILURE_RATE DESC LIMIT 3
"""

TOP_ERRORS = f"""
SELECT d.DESCRIPTION, COUNT(*) AS cnt
FROM {T}.FACT_QUALITY_EVENTS e
JOIN {T}.DTC_BATTERY_ERROR_CODES d ON e.DTC_ERROR_CODE = d.ERROR_ID
WHERE e.HAS_ERROR = 1 GROUP BY d.DESCRIPTION ORDER BY cnt DESC LIMIT 5
"""
