"""Centralized SQL queries for the Automotive Intelligence Platform."""

DATABASE = "VEHICLE_QUALITY_DB"
SCHEMA = "PUBLIC"

# -- Executive Dashboard --

KPI_OVERVIEW = f"""
SELECT
    COUNT(DISTINCT CAR_ID) AS total_vehicles,
    COUNT(*) AS total_events,
    SUM(HAS_ERROR) AS total_failures,
    ROUND(SUM(HAS_ERROR)::FLOAT / NULLIF(COUNT(*), 0) * 100, 2) AS failure_rate_pct,
    COUNT(DISTINCT CASE WHEN HAS_ERROR = 1 THEN CAR_ID END) AS vehicles_with_failures
FROM {DATABASE}.{SCHEMA}.FACT_QUALITY_EVENTS
"""

WEEKLY_FAILURE_TREND = f"""
SELECT
    WEEK_START,
    SUM(TOTAL_EVENTS) AS total_events,
    SUM(FAILURE_COUNT) AS failures,
    ROUND(SUM(FAILURE_COUNT)::FLOAT / NULLIF(SUM(TOTAL_EVENTS), 0) * 100, 2) AS failure_rate_pct,
    SUM(VEHICLES_AFFECTED) AS vehicles_affected
FROM {DATABASE}.{SCHEMA}.AGG_FAILURE_RATES
GROUP BY WEEK_START
ORDER BY WEEK_START
"""

ERROR_CODE_DISTRIBUTION = f"""
SELECT
    e.DTC_CODE,
    d.DESCRIPTION AS error_description,
    COUNT(*) AS event_count
FROM {DATABASE}.{SCHEMA}.FACT_QUALITY_EVENTS e
JOIN {DATABASE}.{SCHEMA}.DTC_BATTERY_ERROR_CODES d
    ON e.DTC_ERROR_CODE = d.ERROR_ID
WHERE e.HAS_ERROR = 1
GROUP BY e.DTC_CODE, d.DESCRIPTION
ORDER BY event_count DESC
"""

FAILURES_BY_STATE = f"""
SELECT
    STATE,
    STATE_AB,
    COUNT(*) AS failure_count,
    AVG(AVG_TEMP_F) AS avg_temp
FROM {DATABASE}.{SCHEMA}.FACT_QUALITY_EVENTS
WHERE HAS_ERROR = 1
GROUP BY STATE, STATE_AB
ORDER BY failure_count DESC
"""

# -- Supplier Analytics --

SUPPLIER_FAILURE_RATES = f"""
SELECT
    SUPPLIER_NAME,
    SUM(TOTAL_EVENTS) AS total_events,
    SUM(FAILURE_COUNT) AS total_failures,
    ROUND(SUM(FAILURE_COUNT)::FLOAT / NULLIF(SUM(TOTAL_EVENTS), 0) * 100, 2) AS failure_rate_pct,
    SUM(VEHICLES_AFFECTED) AS vehicles_affected,
    ROUND(AVG(AVG_TEMPERATURE_F), 1) AS avg_temp_f,
    ROUND(AVG(AVG_DISTANCE_MILES), 1) AS avg_distance_miles
FROM {DATABASE}.{SCHEMA}.AGG_FAILURE_RATES
GROUP BY SUPPLIER_NAME
ORDER BY failure_rate_pct DESC
"""

SUPPLIER_WEEKLY_TREND = f"""
SELECT
    WEEK_START,
    SUPPLIER_NAME,
    ROUND(SUM(FAILURE_COUNT)::FLOAT / NULLIF(SUM(TOTAL_EVENTS), 0) * 100, 2) AS failure_rate_pct
FROM {DATABASE}.{SCHEMA}.AGG_FAILURE_RATES
GROUP BY WEEK_START, SUPPLIER_NAME
ORDER BY WEEK_START
"""

BATTERY_TYPE_PERFORMANCE = f"""
SELECT
    BATTERY_TYPE_NAME,
    SUPPLIER_NAME,
    SUM(TOTAL_EVENTS) AS total_events,
    SUM(FAILURE_COUNT) AS total_failures,
    ROUND(SUM(FAILURE_COUNT)::FLOAT / NULLIF(SUM(TOTAL_EVENTS), 0) * 100, 2) AS failure_rate_pct
FROM {DATABASE}.{SCHEMA}.AGG_FAILURE_RATES
GROUP BY BATTERY_TYPE_NAME, SUPPLIER_NAME
ORDER BY failure_rate_pct DESC
"""

TEMPERATURE_VS_FAILURES = f"""
SELECT
    ROUND(AVG_TEMPERATURE_F, 0) AS temp_bucket,
    SUM(FAILURE_COUNT) AS failures,
    SUM(TOTAL_EVENTS) AS total_events,
    ROUND(SUM(FAILURE_COUNT)::FLOAT / NULLIF(SUM(TOTAL_EVENTS), 0) * 100, 2) AS failure_rate_pct
FROM {DATABASE}.{SCHEMA}.AGG_FAILURE_RATES
WHERE AVG_TEMPERATURE_F IS NOT NULL
GROUP BY temp_bucket
ORDER BY temp_bucket
"""

# -- Forecasting --

FORECAST_DATA = f"""
SELECT
    SERIES AS part_number,
    TS AS forecast_date,
    FORECAST AS predicted_failures,
    LOWER_BOUND,
    UPPER_BOUND
FROM {DATABASE}.{SCHEMA}.FORECAST_FAILURES_30D
ORDER BY SERIES, TS
"""

HISTORICAL_FAILURES = f"""
SELECT
    PART_NUMBER AS part_number,
    WEEK_START AS event_date,
    FAILURE_COUNT AS actual_failures
FROM {DATABASE}.{SCHEMA}.AGG_FAILURE_RATES
ORDER BY PART_NUMBER, WEEK_START
"""

# -- Vehicle Lookup --

VEHICLE_SEARCH = """
SELECT
    v.CAR_ID, v.VIN, v.MODEL_YEAR, v.VEHICLE_CONFIG, v.STATE, v.STATE_AB,
    v.PART_NUMBER, v.BATTERY_SERIAL_NUMBER, v.AH, v.AMP_HOURS,
    v.BATTERY_TYPE_ID, v.SUPPLIER_ID, v.TEMP_RANGE_CELSIUS, v.VOLTAGE_RANGE
FROM VEHICLE_QUALITY_DB.PUBLIC.DIM_VEHICLES v
WHERE v.VIN ILIKE '%{vin}%'
LIMIT 20
"""

VEHICLE_EVENTS = """
SELECT
    EVENT_DATE, DTC_CODE, ERROR_DESCRIPTION, HAS_ERROR,
    AVG_TEMP_F, AVG_WIND_SPEED_MPH, DIST_IN_M,
    SUPPLIER_NAME, BATTERY_TYPE_NAME
FROM VEHICLE_QUALITY_DB.PUBLIC.FACT_QUALITY_EVENTS
WHERE CAR_ID = {car_id}
ORDER BY EVENT_DATE DESC
"""

COMPONENT_DETAILS = """
SELECT *
FROM VEHICLE_QUALITY_DB.PUBLIC.DIM_COMPONENTS
WHERE PART_NUMBER = '{part_number}'
"""
